name: Secret Scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  scan:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install detect-secrets
      - name: Install detect-secrets
        run: pip install detect-secrets

      # 4. Run scan against baseline
      - name: Scan for secrets
        run: detect-secrets scan --baseline .secrets.baseline --all-files
